### ISSUE TITLE
Integration twitter

### ISSUE THREAD

**Issue by Greenns** [ScreamShot/ScreamShot#1]
Hello

Is it possible to integrate twitter in the server side ?

https://dev.twitter.com/cards/types/photo

**Comment by PunKeel** [comment]
It is already done, but I need to sort things before open sourcing them (there will be `ScreamShot/<xxx-endpoint>` repositories)

**Comment by PunKeel** [comment]
Done, here it is: https://github.com/ScreamShot/php-endpoint

Thanks for using ScreamShot!
